### ISSUE TITLE
Runs "lose communication" and fail at scale

### ISSUE THREAD

**Issue by tonycurtis** [openpmix/prrte#681] opened 2020-11-04 14:21 UTC
Thank you for taking the time to submit an issue!

## Background information

Larger mpirun/prte runs generate a "lost communication" error, both with standalone PRRTE and ompi out of github.

Not seeing errors with ompi 4.0.5.

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

github master @ 8cc88dd7f7627c2238b9b7bac2e68fe5a6092f7e

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

github master @ 471554b2dd9115960e6b1108add7c5b0c96f262b

### Please describe the system on which you are running

* Operating system/version: CentOS 8
* Computer hardware: ARM (a64fx)
* Network type: IB

-----------------------------

## Details of the problem

Scaling runs up above around 80 nodes consistently does this:

```
PRTE has lost communication with a remote daemon.

  HNP daemon   : [[47075,0],0] on node fj-debug1
  Remote daemon: [[47075,0],27] on node fj078

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
```

**Comment by jjhursey** [comment] 2020-11-05 22:08
I did some poking a this with our CI scale feature and reproduced something similar at 75 nodes (it has a bit of a stack before it):
 * https://github.com/openpmix/prrte/pull/684#issuecomment-722673605

When you get this error did it give you any other stack information?

**Comment by tonycurtis** [comment] 2020-11-06 17:13
No, just that message.  Now it's not happening at all (?) but I am getting a probably unrelated message, e.g.
```
A requested component was not found, or was unable to be opened.  This
means that this component is either not installed or is unable to be
used on your system (e.g., sometimes this means that shared libraries
that the component requires are unable to be found/loaded).  Note that
PMIx stopped checking at the first component that it did not find.

Host:      fj019
Framework: ptl
Component: usock
```

**Comment by rhc54** [comment] 2020-11-06 17:16
Yeah, that is unrelated. Is it coming from PRRTE or from your app? If the latter, is it linked against the latest PMIx (the same one being used by PRRTE)?

Not happening implies that this might be a race condition...if possible, might be worth running it multiple times and see if it appears.

**Comment by tonycurtis** [comment] 2020-11-06 17:18
PMIx server is from ompi 4.0.5.  PMIx client is github HEAD.  No messages with PMIx 3.2.0, so guessing it is from PMIx HEAD.

**Comment by rhc54** [comment] 2020-11-06 17:19
Ah - that explains it. You can ignore it - these are not the droids you care about.

**Comment by tonycurtis** [comment] 2020-11-06 17:20
OK.  Will this self-resolve, then?

(Waves hand in a mysterious manner)

**Comment by rhc54** [comment] 2020-11-06 17:22
Yes/no - I need to put an if statement in the correct place so it shuts up unless we are trying to generate it.

**Comment by tonycurtis** [comment] 2020-11-06 17:23
I'll just ignore it for now, then...(thnx)

**Comment by rhc54** [comment] 2020-11-22 22:29
This might be fixed by https://github.com/openpmix/prrte/pull/689 - please give it a try after that gets committed and see.

**Comment by tonycurtis** [comment] 2020-12-16 20:11
I'm now getting failures at > 64 nodes.

(Suspicious number)

**Comment by rhc54** [comment] 2021-02-19 18:45
Can I assume that you are no longer seeing failures at scale?

**Comment by tonycurtis** [comment] 2021-02-19 18:53
> On Feb 19, 2021, at 1:45 PM, Ralph Castain <notifications@github.com> wrote:
> 
> 
> Can I assume that you are no longer seeing failures at scale?
> 

Sadly no, always fails > 64 nodes (regardless of ranks-per-node).

Tested with PRRTE HEAD as of 10 minutes ago: prterun hello world MPI on 65 nodes, 1 rank-per-node.

PRTE has lost communication with a remote daemon.

  HNP daemon   : [prterun-fj-debug2-17276@0,0] on node fj-debug2
  Remote daemon: [prterun-fj-debug2-17276@0,1] on node fj065

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.

OMPI 4.x works fine.  Latest OMPI HEAD is segfaulting at the moment at any size.

Let me know if you need more info.

Tony

**Comment by rhc54** [comment] 2021-02-19 19:02
Hmm...very odd. We aren't seeing this elsewhere. I'll try to find a way to replicate

**Comment by tonycurtis** [comment] 2021-02-19 19:58
> On Feb 19, 2021, at 2:02 PM, Ralph Castain <notifications@github.com> wrote:
> 
> 
> Hmm...very odd. We aren't seeing this elsewhere. I'll try to find a way to replicate
> 

BTW the error message appears instantly.  Are there some TCP-related timeout params I could play with?


Tony

**Closed** 2021-02-19 20:53 UTC

**Comment by acolinisi** [comment] 2021-03-03 22:26
At risk of piling unrelated issues, I had the same symptom of "lost communication" only for jobs above a certain rank count. The workaround was to force `routed direct` instead of the binomial/radix default (and, --mca routed direct was not enough because it somehow got overriden to the default, so had to exclude the other variants at build time: ./autogen.pl --include routed-direct). The underlying issue was that the worker nodes where trying to send messages to nodes that weren't known to them -- the log suggested that the non-direct routed logic was broken. There are old (closed) issues about this, that's how I got to the workaround.
