### ISSUE TITLE
Need help to debug 100% cpu utilization for prte server daemon 

### ISSUE THREAD

**Issue by darbyShaw** [openpmix/prrte#1615] opened 2022-12-14 17:09 UTC
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference RTE (PRRTE) are you using? (e.g., v2.0, v3.0, git master @ hash, etc.)
git master @ 166d8a3f85ba2b15c619e9df1ff0ba20f871a4cc
##### What version of PMIx are you using? (e.g., v4.2.0, git branch name and hash, etc.)
git master @ eb8175222344d58ec9f16649e4b7a7de60cda440
### Please describe the system on which you are running

* Operating system/version: Oracle Linux Server release 8.6
* Computer hardware: x86_64
* Network type:

-----------------------------

## Details of the problem
I would like to debug 100% cpu utilization for prte server daemon on a single node with 16 cores.
The server process blocks completely looping somewhere, does not process client requests and stops forwarding IO from the spawned job's procs to the prun tool.  

I run the server using: 
```shell
shell$ prte --host login1:16 --report-pid local_pid --debug-daemons --leave-session-attached --pmixmca pmix_server_connect_verbose 5 --prtemca pmix_server_verbose 5
```
I have a client application that starts with 16 processes but the processes leave the job at different times and call
PMIx_Finalize.
```shell
shell$ prun -n 16 --pid file:local_pid test_swe_local.sh
```
At some point during execution, the IOF forwarding stops at the server, and commands from clients are not processed but the daemon shows 100% cpu utilization and attaching strace to the daemon reports the following:
```shell
shell$ strace -f -p 1531620 (pid of prte server daemon on the node)
strace: Process 1531620 attached with 20 threads
[pid 1531687] epoll_wait(81,  <unfinished ...>
[pid 1531680] epoll_wait(53,  <unfinished ...>
[pid 1531623] select(19, [17 18], NULL, NULL, {tv_sec=3510, tv_usec=292426} <unfinished ...>
[pid 1531681] epoll_wait(57,  <unfinished ...>
[pid 1531679] epoll_wait(49,  <unfinished ...>
[pid 1531678] epoll_wait(45,  <unfinished ...>
[pid 1531676] epoll_wait(37,  <unfinished ...>
[pid 1531675] epoll_wait(33,  <unfinished ...>
[pid 1531674] epoll_wait(29,  <unfinished ...>
[pid 1531673] epoll_wait(25,  <unfinished ...>
[pid 1531672] epoll_wait(21,  <unfinished ...>
[pid 1531620] futex(0xebc530, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 1531686] epoll_wait(77,  <unfinished ...>
[pid 1531685] epoll_wait(73,  <unfinished ...>
[pid 1531683] epoll_wait(65,  <unfinished ...>
[pid 1531682] epoll_wait(61,  <unfinished ...>
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=0, tv_usec=144395} <unfinished ...>
[pid 1531684] epoll_wait(69,  <unfinished ...>
[pid 1531677] epoll_wait(41,  <unfinished ...>
[pid 1531622] <... select resumed>)     = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}) = 0 (Timeout)
[pid 1531622] select(16, [14 15], NULL, NULL, {tv_sec=2, tv_usec=0}
```
I would like to ask for help in order to debug the reason for the prte daemon to loop continuously without serving client
requests or forwarding IO from the spawned processes.
Thank you very much in advance.

**Comment by rhc54** [comment] 2022-12-14 17:28
Do you have a reproducer I can try? This could get a little tricky (race conditions can be difficult). A few things I notice off-hand:

* I see 16 `epoll_wait` calls that are unfinished - are all 16 processes dead at this time? It looks like they might be dead but not being reaped, which is one reason `prte` would hang (as it doesn't realize its children are gone)
* I see 13 calls to `select`, two of which are labeled as `unfinished`. Not sure what that might mean
* You are using Oracle Linux - is that what used to be called Solaris? Or is this really a Linux variant? I ask because Solaris had some "interesting" different behaviors that might make it hard for me to reproduce locally.

You can work around the failure to forward IO by directing `prte` to put the app procs' output into files. See `prun --help output` for details. I would add some debug to the app (if possible) to track where it is in its work - e.g., has it called finalize and is waiting before exiting.

You can also set the `--pmixmca pmix_server_iof_verbose 5` param on `prte` and `--pmixmca pmix_client_iof_verbose 5` param on `prun` to see what the IOF subsystem is doing on each side. It _sounds_ like something is sticking in that subsystem, but that is just a guess.

**Comment by darbyShaw** [comment] 2022-12-14 20:56
I am not sure I can provide a reproducer but I will try. Meanwhile,

- The 16 processes are not dead. 14 are dead and the rest 2 cannot finish because of the blocked server.
- The select calls are not only 13. It keeps looping on select every 2 seconds.
- It is a Linux variant : https://www.oracle.com/linux/
- I tried to redirect output using --output filename=something:nocopy but it still forwards the output to the prun tool. Could you please tell me how to avoid the forwarding to std streams?
- I tried both --pmixmca pmix_server_iof_verbose 5 and --pmixmca pmix_client_iof_verbose 5. Both seem to stop printing anything the moment prte hangs.

**Comment by rhc54** [comment] 2022-12-15 04:35
> * I tried to redirect output using --output filename=something:nocopy but it still forwards the output to the prun tool. Could you please tell me how to avoid the forwarding to std streams?

It shouldn't be forwarding it if you specified `nocopy`. I'll have to take a look

> I tried both --pmixmca pmix_server_iof_verbose 5 and --pmixmca pmix_client_iof_verbose 5. Both seem to stop printing anything the moment prte hangs.

Yes, they will - if prte is hung, then it cannot print diagnostics as nothing is executing. It is the trace leading up to the hang that might tell us something.

> I am not sure of debugging further since I get no output from the application after prte hangs due to io forwarding not happening.

If you cannot provide a reproducer, can you provide a description of what your application does? It sounds like you have one process (rank=0) that is reading `stdin`, and the other processes effectively output some text and terminate at somewhat random (i.e., not synchronized) times. Is that close? If I have a basic description, I can probably fake something that might reproduce what you are seeing.

**Comment by darbyShaw** [comment] 2022-12-15 09:11
> > * I tried to redirect output using --output filename=something:nocopy but it still forwards the output to the prun tool. Could you please tell me how to avoid the forwarding to std streams?
> 
> It shouldn't be forwarding it if you specified `nocopy`. I'll have to take a look
> 
Alright. Thank you.
> > I tried both --pmixmca pmix_server_iof_verbose 5 and --pmixmca pmix_client_iof_verbose 5. Both seem to stop printing anything the moment prte hangs.
> 
> Yes, they will - if prte is hung, then it cannot print diagnostics as nothing is executing. It is the trace leading up to the hang that might tell us something.
> 
I checked the trace before the hang. There is nothing unusual. I added a few debugs there to detect if the IOF_COMPLETE event is detected when a process terminates. The event is detected and the processes terminate normally.

> > I am not sure of debugging further since I get no output from the application after prte hangs due to io forwarding not happening.
> 
> If you cannot provide a reproducer, can you provide a description of what your application does? It sounds like you have one process (rank=0) that is reading `stdin`, and the other processes effectively output some text and terminate at somewhat random (i.e., not synchronized) times. Is that close? If I have a basic description, I can probably fake something that might reproduce what you are seeing.

Yes. That is close enough. I ran perf-top on the prte daemon to check what part of the code it is looping on. I couldn't get anything concrete.
```
Samples: 7M of event 'cycles:u', 100000 Hz, Event count (approx.): 40058542908 lost: 0/0 drop: 0/19
Overhead  Shared Object                   Symbol
  33.63%  libevent_core-2.1.so.6.0.2      [.] event_callback_activate_nolock_
  20.04%  libevent_core-2.1.so.6.0.2      [.] event_queue_remove_active
  18.13%  libevent_core-2.1.so.6.0.2      [.] event_del_nolock_
  12.12%  libevent_core-2.1.so.6.0.2      [.] event_active_nolock_
   8.67%  libevent_core-2.1.so.6.0.2      [.] event_base_loop
   1.27%  libevent_pthreads-2.1.so.6.0.2  [.] evthread_posix_get_id
   1.26%  libevent_pthreads-2.1.so.6.0.2  [.] pthread_self@plt
   1.25%  libpthread-2.28.so              [.] pthread_self@GLIBC_2.2.5
   1.23%  libevent_core-2.1.so.6.0.2      [.] event_del_nolock_@plt
   1.21%  libevent_core-2.1.so.6.0.2      [.] event_callback_activate_nolock_@plt
   1.21%  libevent_core-2.1.so.6.0.2      [.] event_active_nolock_@plt
   0.00%  [kernel]                        [k] 0xffffffff902002bc
   0.00%  [kernel]                        [k] 0xffffffff90200dd7
   0.00%  libpmix.so.0.0.0                [.] listen_thread
   0.00%  libc-2.28.so                    [.] __libc_disable_asynccancel

```

**Comment by rhc54** [comment] 2022-12-15 14:10
Sorry - a few more questions.

How many nodes are involved?

How large is the input file you are feeding into stdin?

If you have the process open the file and read it directly, does the problem go away?

**Comment by rhc54** [comment] 2022-12-15 15:25
Did a quick check of the "nocopy" qualifier and it seems to be working correctly:
```shell
$ prterun -n 2 --output file=foo:nocopy hostname
$ cat foo*
Ralphs-iMac-2.local
Ralphs-iMac-2.local
$
```
This was only on one node, so that could be a difference. One thing of note: your clone of PRRTE and PMIx are very old. Could you please update to today's HEAD on both repos? There have been a lot of bug fixes since the version you are using, and that might explain the difference.

**Comment by darbyShaw** [comment] 2022-12-15 17:02
I now updated both PMIx and PRRTE to the git master head. The problem still persists.
I realize after trying out several things that the problem is not associated with IO forwarding.
One thing I missed to mention is that at different times, I form groups of processes using PMIx_group_construct_nb and terminate the processes not part of the group.  So suppose I start with 16 processes, after a checkpoint I terminate 8 of them and form a PMIx group out of the remaining 8.
When I do not use PMIx_group_construct_nb everything just works fine. I will try to write something down to reproduce it but it might take some time. Either there is something odd happening at the server or I might have got something wrong in the construction procedure (though I cross checked a few times).

**Comment by rhc54** [comment] 2022-12-15 17:06
Hmmm...ok, good to know. I just finished creating a stress-test for the IOF subsystem and everything worked fine, even with gigabyte files.

Check that you are not calling any blocking PMIx functions while inside the group construct callback function - that's a typical mistake. Does this fail during the first iteration of that procedure? Or after some number of them?

**Comment by darbyShaw** [comment] 2022-12-15 17:14
No I do not have any blocking calls in the callback. That's the first thing I checked.
The strange thing is it always fails in the last phase of simulation. So suppose I use two phases, first with 16 procs and second with 8 procs, then it hangs in the second phase after some iterations. If I have four phases of 16, 8, 4, 2 processes the first 3 phases of group construct and further processing work just fine and the last phase just hangs.

**Comment by rhc54** [comment] 2022-12-15 17:23
Hmmm...that sounds suspiciously like something in the app. I don't know why `prte` would hang, though I wonder if it actually hasn't and only looks that way because the app has hung? Is it possible that you get the last iteration off by one - i.e., for your four phase case, is it possible that your code thinks there will be 3 processes in the final group?

I can poke at it a bit to ensure we aren't messing up somewhere. Interesting use-case. Do all the procs forming the new group call `PMIx_Group_construct_nb`? If so, do they all call with the participants in the same order?

**Comment by rhc54** [comment] 2022-12-15 17:34
Hopefully final question. When the remaining procs call `PMIx_Group_construct_nb`, do they pass the identifiers of each process that should join? Or are you passing a wildcard rank to mean "all procs that are still alive"?

**Comment by darbyShaw** [comment] 2022-12-15 17:51
No I specifically add the identifiers.
```
PMIX_PROC_CREATE (group_procs, total_procs);
for (int i = 0; i < current_proc_count; i++)
      {
        if (proc_rank[i].stay_alive == /*should stay allive*/)
        {
          PMIX_PROC_LOAD (&group_procs[j], proc_rank[i].nspace, proc_rank[i].rank);
          DEBUG_PRINT_ERROR ("Added process %d with namespace %s to group proc", 
          group_procs[j].rank, group_procs[j].nspace);
        }
      }
      pmix_info_t group_info;
      size_t ndirs;
      pmix_info_t *results = NULL;
      PMIX_INFO_LOAD (&group_info, PMIX_TIMEOUT, &pmix_timeout, PMIX_UINT32);
      rc = PMIx_Group_construct_nb (group_name, group_procs, total_procs,
                                    &group_info, 1,
                                    group_construct_complete,
                                    (void *)&group_cb_data);
      if (rc != PMIX_SUCCESS)
      {
        DEBUG_PRINT_ERROR ("Failed to  construct group \
                                  %d", rc);
        return ERROR;
      }
      PMIX_PROC_FREE (group_procs, total_procs);
```

**Comment by rhc54** [comment] 2022-12-15 17:55
Hmmm...wait a minute. You are free'ing the `group_procs` array immediately after the call to `PMIx_Group_construct_nb`. You cannot do that - you have to wait until the callback function is executed. Same with the `group_info`.

**Comment by darbyShaw** [comment] 2022-12-15 18:02
That doesn't work either. I tried a blocking call instead (this is not inside a callback) and removed the free. The blocking call does not work either.
```
PMIX_PROC_CREATE (group_procs, total_procs);
for (int i = 0; i < current_proc_count; i++)
      {
        if (proc_rank[i].stay_alive == /*should stay allive*/)
        {
          PMIX_PROC_LOAD (&group_procs[j], proc_rank[i].nspace, proc_rank[i].rank);
          DEBUG_PRINT_ERROR ("Added process %d with namespace %s to group proc", 
          group_procs[j].rank, group_procs[j].nspace);
        }
      }
      pmix_info_t group_info;
      size_t ndirs;
      pmix_info_t *results = NULL;
      PMIX_INFO_LOAD (&group_info, PMIX_TIMEOUT, &pmix_timeout, PMIX_UINT32);
      rc = PMIx_Group_construct (group_name, group_procs,total_procs, &group_info, 1, &results, &ndirs);
      if (rc != PMIX_SUCCESS)
      {
        DEBUG_PRINT_ERROR ("Failed to  construct group \
                                  %d", rc);
        return ERROR;
      }
      
```

**Comment by rhc54** [comment] 2022-12-15 18:17
Okay, let me create a reproducer and I'll give it a try. Are you using more than one node (it matters because of the way PRRTE works)?

**Comment by darbyShaw** [comment] 2022-12-15 18:19
No just a single node with 16 cores.

**Comment by darbyShaw** [comment] 2022-12-15 18:24
I am not sure but it looks like time out (PMIX_TIMEOUT) in group construct is the culprit. I will try a few things again.

**Comment by rhc54** [comment] 2022-12-15 18:52
Looks like PRRTE is ignoring the timeout attribute - are you relying on it? I should probably implement support for it anyway.

**Comment by rhc54** [comment] 2022-12-15 19:06
Uhoh - looks like PMIx _server_ is implementing it. Let me look at it a bit - something about it seems off to me. Meantime, if you remove the timeout, does it work?

**Comment by rhc54** [comment] 2022-12-15 19:42
Yeah, I need to modify this - we should be letting PRRTE handle the timeout. Otherwise, we get into a race condition where the timeout can remove the tracker while PRRTE is still working on the construct, leaving PRRTE calling back with a no-longer-valid object. This will take a little bit. Meantime, I would recommend trying without the timeout and seeing if that helps.

**Comment by rhc54** [comment] 2022-12-15 22:25
So, a little more info after poking around a bit. Since all the procs here are on one node, PRRTE was never actually involved. A completely local group construct is handled by the PMIx server library itself (which while housed in the `prte` process, is running independently of it). I'm therefore inclined to suspect the timeout as being the culprit here.

I think I can build a simple reproducer that can act as a future test - will update later.

**Comment by rhc54** [comment] 2022-12-16 05:16
So I wrote a reproducer (shown below) and it seems to work fine with the changes I committed to PMIx and PRRTE. Please let me know if the reproducer looks roughly correct, and update your repos to see if that fixes your problem.
```c
    /* LOOP UNTIL ALL PROCS FINALIZE */
    newprocs = nprocs;
    while (1) {
        /* DIVIDE NPROCS / 2 - HALF THE PROCS CALL FINALIZE AND TERMINATE
         * OTHER HALF CALL GROUP_CONSTRUCT, ENSURE UNIQUE GROUP ID! */
        newprocs = newprocs / 2;
        if (newprocs <= myproc.rank || 2 > newprocs) {
            break;
        }
        PMIX_PROC_CREATE(procs, newprocs);
        for (n=0; n < newprocs; n++) {
            PMIX_LOAD_PROCID(&procs[n], myproc.nspace, n);
        }
        asprintf(&grpid, "MYGRP%d", (int)newprocs);
        rc = PMIx_Group_construct(grpid, procs, newprocs, NULL, 0, &results, &nresults);
        if (PMIX_SUCCESS != rc) {
            fprintf(stderr, "[%s:%d]: PMIx_Group_construct failed: %s\n",
                    myproc.nspace, myproc.rank, PMIx_Error_string(rc));
            goto done;
        } else if (0 == myproc.rank) {
            fprintf(stderr, "[%s:%d]: PMIx_Group_construct for group %s succeeded\n",
                    myproc.nspace, myproc.rank, grpid);
        }

        /* DELAY FOR AWHILE TO SIMULATE ACTION */
        sleep(2);

        /* CALL GROUP_DESTRUCT */
        rc = PMIx_Group_destruct(grpid, NULL, 0);
        if (PMIX_SUCCESS != rc) {
            fprintf(stderr, "[%s:%d]: PMIx_Group_destruct failed: %s\n", myproc.nspace,
                    myproc.rank, PMIx_Error_string(rc));
            goto done;
        }

        free(grpid);
        PMIX_PROC_FREE(procs, newprocs);
    }
    /* END LOOP */
```

**Comment by darbyShaw** [comment] 2022-12-16 10:47
To reproduce the issue, a timeout has to be set in the group construct procedure and some local activity has to be done till the time out is hit. After that there is complete blocking of the server and the client can neither get any IO forwarded nor make any  PMIx requests that need to be sent to the server.

I see that things work now with the new repos. Thank you very much!

**Closed** 2022-12-16 15:01 UTC
