### ISSUE TITLE
pterm name collision

### ISSUE THREAD

**Issue by amckinstry** [openpmix/prrte#1849] opened 2023-11-17 08:23 UTC
Hi, I'm maintainer for openmpi in Debian/Ubuntu.

I'm testing openmpi 5.0.0, which includes prrte.
Now openmpi-5.0.0 includes pterm and pterm.1. Unfortunately there is a name collision with other software, the pterm client for putty: https://tracker.debian.org/pkg/putty

Can the name be changed?

thanks
Alastair McKinstry

**Comment by rhc54** [comment] 2023-11-17 09:56
Duplicate of #1836 - please see discussion there.

**Closed by rhc54** 2023-11-17 09:56 UTC
