### ISSUE TITLE
need to implement --display-allocation and other options that use to exist with orte

### ISSUE THREAD

**Issue by hppritcha** [openpmix/prrte#421] opened 2020-02-27 18:34 UTC
We are trying to debug some problems we're seeing on a slurm cluster and prte not seeming to recognize our allocation.  In the course of trying to do this, noticed quite a few of the debug options available with the old orte aren't present.  Among these are

- display-allocation
- display-map
- debug-daemons

This list is probably not complete.

**Comment by jjhursey** [comment] 2020-02-27 18:52
Mostly a duplicate of Issue #388 - we should combine these lists

**Comment by bosilca** [comment] 2020-02-27 23:31
--display-topo
--do-not-launch

**Comment by rhc54** [comment] 2020-03-06 19:43
These have all now been implemented and brought to OMPI in https://github.com/open-mpi/ompi/pull/7498

**Closed by rhc54** 2020-03-06 19:43 UTC
